# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('teacher_id', models.IntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['teacher_id']),
                    models.Index(fields=['is_published']),
                ],
            },
        ),
        migrations.CreateModel(
            name='CourseDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_id', models.IntegerField()),
                ('order_index', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=models.CASCADE, related_name='course_decks', to='courses.course')),
            ],
            options={
                'ordering': ['order_index', 'id'],
                'constraints': [
                    models.UniqueConstraint(fields=['course', 'deck_id'], name='unique_course_deck'),
                ],
                'indexes': [
                    models.Index(fields=['course', 'order_index']),
                ],
            },
        ),
    ]
