# Generated by Django 5.2.8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['student_id'], name='enrollment_student_id_idx'),
                    models.Index(fields=['course', 'student_id'], name='enrol_course_student_id_idx'),
                ],
                'unique_together': {('course', 'student_id')},
            },
        ),
        migrations.CreateModel(
            name='DeckProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('course_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='courses.coursedeck')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_progresses', to='enrollments.enrollment')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['enrollment', 'is_completed'], name='deck_prog_enroll_is_compl_idx'),
                ],
                'unique_together': {('enrollment', 'course_deck')},
            },
        ),
    ]
